project:
  type: website

website:
  title: "blumsblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/profzo
format:
  html:
    toc: true
    df-print: paged
    theme: lux
    css: styles.css

editor: visual

